### PR TITLE
Tolerate importing lines with badly formatted times by skipping them

### PR DESCRIPTION
**Pull request by risseraka**
Here's my proposed fix for this issue: https://github.com/fnogatz/transportation/issues/8.

Cheers,

### CODE REVIEW

**Comment by fnogatz** [comment]
Hi Adrien,

thank you for your Pull Request! As I'm currently moving flat, I will look into as recently as the end of the next week :)

**Comment by risseraka** [comment]
No worries, I'm already using this quick fix in production, works like a
charm.

Looking forward to your thoughts in that.

Cheers,

**Comment by fnogatz** [comment]
It's merged and published as `v1.1.0` on npm. I've added a test. The importer will now call `console.warn()` for non-valid stop times.

**Comment by risseraka** [comment]
Good stuff, thanks!

**Pull request merged**
